<header>
        <div class="headercontainer">
            <div class="logocontainer">
                <a href="./"><h2>PromptGPT</h2></a>
            </div>
            <div class="menucontainer">
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="/about.html">About</a></li>
                    <li><a href="/prompts.html">Prompts</a></li>
                    <li><a href="/submission.html">Submission</a></li>
                    
                </ul>
            </div>
            <div class="ctacontainer">
                <p>Welcome First Name</p>
            </div>
        </div>
    </header>